version: '3.8'

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - SocialMedia_network

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29091,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29091,PLAINTEXT_HOST://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - SocialMedia_network

  userService:
    build: ./services/user-service
    container_name: SocialMedia-user-service_c
    image: abshar777/socialmedia-user-service
    restart: unless-stopped
    env_file:
      - ./services/user-service/.env
    depends_on:
      - kafka
    ports:
      - 3000:3000
    networks: 
      - SocialMedia_network
    develop:
      watch:
        - action: sync
          path: ./services/user-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/user-service/package.json

  postService:
    build: ./services/post-service
    container_name: SocialMedia-post-service_c
    image: abshar777/socialmedia-post-service
    restart: unless-stopped
    env_file:
      - ./services/post-service/.env
    depends_on:
      - kafka
    ports:
      - 3001:3001
    networks: 
      - SocialMedia_network
    develop:
      watch:
        - action: sync
          path: ./services/post-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/post-service/package.json


  storyService:
    build: ./services/story-service
    container_name: SocialMedia-story-service_c
    image: abshar777/socialmedia-story-service
    restart: unless-stopped
    env_file:
      - ./services/story-service/.env
    depends_on:
      - kafka
    ports:
      - 3002:3002
    networks: 
      - SocialMedia_network
    develop:
      watch:
        - action: sync
          path: ./services/story-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/story-service/package.json


  messageService:
    build: ./services/message-service
    container_name: SocialMedia-message-service_c
    image: abshar777/socialmedia-message-service
    restart: unless-stopped
    env_file:
      - ./services/message-service/.env
    depends_on:
      - kafka
    ports:
      - 3003:3003
    networks: 
      - SocialMedia_network
    develop:
      watch:
        - action: sync
          path: ./message-service
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./message-service/package.json


  nginx:
    build: ./gateway
    container_name: SocialMedia-nginx-gateway
    image: abshar777/socialmedia-nginx-gateway
    ports:
      - 8000:80
    networks:
      - SocialMedia_network
    depends_on:
      - userService
      - postService
      - storyService
      - messageService

networks:
  SocialMedia_network:
    driver: bridge
